on:
  schedule:
    - cron:  "*/15 14-20 * * TUE"
  workflow_dispatch:

name: covid-scraper

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          packages: |
            any::gh
            any::pkgdown
            any::dplyr
            any::tidyr
            any::readr
            any::knitr
            any::tidyverse
            any::zoo
            devtools::install_github("Chicago/RSocrata")

      - name: Execute Script
        run: |
          Rscript "covid-repos/script.R"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-
