on:
  schedule:
    - cron:  "* * * * *"
  workflow_dispatch:

name: covid-scraper

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::gh
            any::dplyr
            any::tidyr
            any::readr
            any::knitr
            any::tidyverse
            any::googlesheets4
            any::RSocrata

      - name: Execute Script
        run: |
          Rscript "covid-repos/script.R"
